### ISSUE TITLE
热力图canvas未绘制

### ISSUE THREAD

**Issue by zhumw** [cesium-plugin/cesium-heatmap-es6#1]
#距离过近的点位，heatmap-canvas并未绘制
例const pointss = [
            {x: 118.9229, y: 32.121432, value: 1},
            {x: 119.8205, y: 32.021040, value: 1},
            {x: 118.8202, y: 32.021351, value: 1},
            {x: 118.8218, y: 32.021414, value: 1},
            {x: 118.8223, y: 32.017125, value: 1},
            {x: 118.8218, y: 32.020932, value: 1},
            {x: 119.8202, y: 32.021281, value: 1},
        ]

**Comment by ONEGISER** [comment]
热度图插件heatmap版本得问题   无奈之下离线使用此库    搞了元宵节半天时间终于修复

**Comment by ONEGISER** [comment]
> #距离过近的点位，heatmap-canvas并未绘制 例const pointss = [ {x: 118.9229, y: 32.121432, value: 1}, {x: 119.8205, y: 32.021040, value: 1}, {x: 118.8202, y: 32.021351, value: 1}, {x: 118.8218, y: 32.021414, value: 1}, {x: 118.8223, y: 32.017125, value: 1}, {x: 118.8218, y: 32.020932, value: 1}, {x: 119.8202, y: 32.021281, value: 1}, ]

热度图插件heatmap版本得问题 无奈之下离线使用此库 搞了元宵节半天时间终于修复
