### ISSUE TITLE
关于不同高度处热力值是否不同的问题

### ISSUE THREAD

**Issue by Maksimhan** [cesium-plugin/cesium-heatmap-es6#2]
您好，
我想请问以下此代码库展示的三维热力图，在同一个地理坐标下，不同高度处的值都是一样的吗？因为我想尝试一下不同高度处的值也不同，不知道您的代码能否实现？
谢谢！

**Comment by Maksimhan** [comment]
Hello!
I would like to ask if the following three-dimensional heatmap displayed in this code base has the same value at different heights under the same geographical coordinate? 
And I wonder if your code can realize the above functions, that is, add the coordinate height to the rendering function of thermal map, which is similar to the effect of point cloud
Thanks!

**Comment by ONEGISER** [comment]
这个倒是可以内部支持，你可以先将对应经纬度的高度获取到，传进去，因为热度图本身不建议去扩展高度热度图

**Comment by ONEGISER** [comment]
> 这个倒是可以内部支持，你可以先将对应经纬度的高度获取到，传进去，因为热度图本身不建议去扩展高度热度图


这个倒是可以内部支持，你可以先将对应经纬度的高度获取到，传进去，因为热度图本身不建议去扩展高度热度图

**Comment by ONEGISER** [comment]
> 您好， 我想请问以下此代码库展示的三维热力图，在同一个地理坐标下，不同高度处的值都是一样的吗？因为我想尝试一下不同高度处的值也不同，不知道您的代码能否实现？ 谢谢！

这个倒是可以内部支持，你可以先将对应经纬度的高度获取到，传进去，因为热度图本身不建议去扩展高度热度图
