### ISSUE TITLE
移除不了

### ISSUE THREAD

**Issue by TBusan** [cesium-plugin/cesium-heatmap-es6#3]
remove() {
        debugger
        if (this.element) {
            document.body.removeChild(this.element);
            this.element = undefined;
            if (this.provider instanceof ImageryLayer) {
                if (this.provider)
                    this.viewer.imageryLayers.remove(this.provider);
                this.createSingleTileImageryLayer();
            }
            else if (this.provider instanceof Primitive) {
                this.viewer.scene.primitives.remove(this.provider);
            }
            // else if (this.provider instanceof Entity) {
            //     this.viewer.scene.primitives.remove(this.provider);
            // }
            else if (this.provider.id == 'heatmap-entity') {
                this.viewer.entities.remove(this.provider);
            }
            if (this.cameraMoveEnd)
                this.viewer.camera.moveEnd.removeEventListener(this.cameraMoveEnd);
        }
    }

没仔细去看原因，个人觉得可能是this.viewer.add()后返回的entity 实例 或者primitive实例    不是插件中的引用类型。  应该是开发中自己用的cesium  跟这个插件引入的cesium版本不一致造成的。 （目前我就直接在添加entity的时候给了一个默认的ID，临时解决的。）

**Comment by ONEGISER** [comment]
![image](https://user-images.githubusercontent.com/20511586/169993744-f8e2bd1a-0bcb-4cf3-9797-ef0c4b598b86.png)
调用cesiumHeatemap.remove()方法即可删除

**Comment by ONEGISER** [comment]
你的Cesium版本是多少？

**Comment by TBusan** [comment]
> 你的Cesium版本是多少？

我自己引用的是1.84   但是插件里面的是1.93  .我直接调用remove()是移除不掉的

**Comment by TBusan** [comment]
> 你的Cesium版本是多少？

它不会进入到    那三个判断里面

**Comment by ONEGISER** [comment]
我排查一下！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cesium-plugin/cesium-heatmap-es6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cesium-plugin/cesium-heatmap-es6] 移除不了 (Issue #3)





  
你的Cesium版本是多少？
  
它不会进入到    那三个判断里面

**Comment by ONEGISER** [comment]
> > 你的Cesium版本是多少？
> 
> 它不会进入到 那三个判断里面

加我微信zpc1305780485

**Comment by ONEGISER** [comment]
> > 你的Cesium版本是多少？
> 
> 它不会进入到 那三个判断里面

我这边用1.84测试了没问题

**Comment by TBusan** [comment]
好呢
