### ISSUE TITLE
报错Cannot assign to read only property 'data' of object '#<ImageData>'

### ISSUE THREAD

**Issue by tingyuxuan2302** [cesium-plugin/cesium-heatmap-es6#5]
cesium版本是1.101.0，引入插件使用报错
![image](https://user-images.githubusercontent.com/22094990/215964525-4303a543-9b75-44cc-a14b-6a800816c1d2.png)

**Comment by tingyuxuan2302** [comment]
已解决，博主，确定这个包是可以直接使用的嘛现在😂，我改了两处源码才能用

**Comment by wenzhihao123** [comment]
> 

兄弟，请教下怎么修改的呀

**Comment by ONEGISER** [comment]
> 已解决，博主，确定这个包是可以直接使用的嘛现在😂，我改了两处源码才能用

您改的是那两处？

**Comment by ONEGISER** [comment]
> > 
> 
> 兄弟，请教下怎么修改的呀
我本地环境没有任何问题，你是怎么使用的？

**Comment by tingyuxuan2302** [comment]
> > 已解决，博主，确定这个包是可以直接使用的嘛现在😂，我改了两处源码才能用
> 
> 您改的是那两处？

要不我直接提pr？

**Comment by tingyuxuan2302** [comment]
> > 已解决，博主，确定这个包是可以直接使用的嘛现在😂，我改了两处源码才能用
> 
> 您改的是那两处？

其中就是图中报错的问题，只读属性问题，可能是cesium版本不同导致的吧，要不我直接提pr？

**Comment by ONEGISER** [comment]
直接一起共建！邀请你了


> > > 已解决，博主，确定这个包是可以直接使用的嘛现在😂，我改了两处源码才能用
> > 
> > 
> > 您改的是那两处？
> 
> 其中就是图中报错的问题，只读属性问题，可能是cesium版本不同导致的吧，要不我直接提pr？

**Comment by tingyuxuan2302** [comment]
> 直接一起共建！邀请你了
> 
> > > > 已解决，博主，确定这个包是可以直接使用的嘛现在😂，我改了两处源码才能用
> > > 
> > > 
> > > 您改的是那两处？
> > 
> > 
> > 其中就是图中报错的问题，只读属性问题，可能是cesium版本不同导致的吧，要不我直接提pr？

好了，pr提交了，合并一下，然后再发个版本试试

**Comment by wenzhihao123** [comment]
@ONEGISER @tingyuxuan2302 大佬们发版本了，通知我下，谢啦

**Comment by ONEGISER** [comment]
> @ONEGISER @tingyuxuan2302 大佬们发版本了，通知我下，谢啦

版本已发
